### ISSUE TITLE
FBX Scene Loading Failed : 'File is corrupted Cube.fbx'

### ISSUE THREAD

**Issue by AnriEU** [EpicGamesExt/BlenderTools#731]
https://epicgamesext.github.io/BlenderTools/send2ue/introduction/quickstart.html

"Now lets run through a basic example with the default cube in your Blender scene."
"A simple test we can try in Blender to make sure this is working is move our cube to our Export collection."
"You should now see the cube in unreal under /untitled category/untitled asset/Cube."

But I see error -
FBX Scene Loading Failed : 'File is corrupted Cube.fbx'
Can't detect import type. No mesh is found or animation track.

Please help!
Unreal 5.3.2
Blender 4.0

**Comment by JoshQuake** [comment]
Here's the latest temporary fixed version https://github.com/EpicGamesExt/BlenderTools/issues/729#issuecomment-2026320080. This was fixed a while ago.

**Comment by philipjc** [comment]
Does this mean, this issue and another duplicate in the issue list can be closed?

**Comment by JoshQuake** [comment]
> Does this mean, this issue and another duplicate in the issue list can be closed? Duplicate? #711

Yeah I guess so. The fix has been merged already.

**Comment by RWOverdijk** [comment]
@JoshQuake The fix does not work, or does not work anymore. 

Blender 4.1.1, still getting the same errors in unreal engine. This issue is still relevant I think
